# Generated by Django 5.0 on 2024-01-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='news/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/videos/')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
