# Generated by Django 5.0 on 2024-01-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsschool',
            name='hashtag',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
