# Generated by Django 5.0 on 2024-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chsb', '0002_alter_innerchsb_grupin_alter_marks_groupin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='fizika',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='geometriya',
            field=models.FloatField(blank=True),
        ),
    ]
