# Generated by Django 5.0 on 2024-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chsb', '0004_marks_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='chsbCount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
