# Generated by Django 5.0 on 2024-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chsb', '0005_marks_chsbcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerchsb',
            name='chsbCount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
