# Generated by Django 5.0 on 2024-01-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chsb', '0006_innerchsb_chsbcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chsblar',
            name='name',
        ),
    ]
