# Generated by Django 5.0 on 2024-01-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chsb', '0008_chsblar_coun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='fizika',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='geometriya',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
