# Generated by Django 5.0 on 2024-01-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chsb', '0009_alter_marks_fizika_alter_marks_geometriya'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='allChsb',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
