# Generated by Django 5.0 on 2024-01-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chsb', '0011_remove_marks_allchsb_alter_marks_grade'),
        ('pupils', '0015_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.students'),
        ),
    ]
