# Generated by Django 5.0 on 2024-01-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0005_delete_teacherregistr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.BigIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
