# Generated by Django 5.0 on 2024-01-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0007_teachers_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yutuqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yutuqlar/')),
                ('about', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('typ', models.CharField(max_length=120)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(upload_to='teacherimages/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Ingliz tili', 'Ingliz Tili'), ('Fizika', 'Fizika'), ('Ona tili va adabiyot', 'Ona tili va adabiyot'), ('Tarix', 'Tarix'), ('Huquq', 'Huquq')], max_length=120),
        ),
    ]
