# Generated by Django 5.0 on 2024-01-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0011_alter_students_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
