# Generated by Django 5.0 on 2024-01-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0013_alter_students_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('501', 501), ('502', 502), ('503', 503), ('601', 601), ('602', 602), ('603', 603), ('701', 701), ('702', 702), ('703', 703), ('801', 801), ('802', 802), ('803', 803), ('901', 901), ('902', 902), ('903', 903), ('1001', 1001), ('1002', 1002), ('1003', 1003), ('11', 11)], max_length=120),
        ),
    ]
